"""Interface and file utilities for the Voice-to-Voice AI Assistant."""

from pathlib import Path
from time import sleep

from whisper.tokenizer import LANGUAGES

from config import (
    APP_TITLE,
    COUNTDOWN_SECONDS,
    DIVIDER_WIDTH,
)


def print_banner() -> None:
    """Display the application title."""

    divider = "=" * DIVIDER_WIDTH

    print()
    print(divider)
    print(APP_TITLE.center(DIVIDER_WIDTH))
    print(divider)
    print()


def wait_for_user() -> None:
    """Wait for the user to begin a voice-assistant session."""

    input("Press ENTER to start the voice assistant...")


def countdown(seconds: int = COUNTDOWN_SECONDS) -> None:
    """Display a countdown before microphone recording begins.

    Args:
        seconds: Number of countdown seconds.

    Raises:
        ValueError: If the countdown duration is negative.
    """
    if seconds < 0:
        raise ValueError(
            "The countdown duration cannot be negative."
        )

    if seconds == 0:
        print()
        print("Speak now!")
        print()
        return

    print()
    print("Recording starts in...")
    print()

    for remaining in range(seconds, 0, -1):
        print(remaining)
        sleep(1)

    print()
    print("Speak now!")
    print()


def print_status(message: str) -> None:
    """Display an application-status message.

    Args:
        message: Status text to display.
    """
    print(message)
    print()


def language_code_to_name(language_code: str) -> str:
    """Convert a Whisper language code into a readable name.

    Args:
        language_code: Language code returned by Whisper.

    Returns:
        A readable language name or the uppercase language code.
    """
    cleaned_code = language_code.strip().lower()

    if not cleaned_code or cleaned_code == "unknown":
        return "Unknown"

    language_name = LANGUAGES.get(cleaned_code)

    if language_name:
        return language_name.title()

    return cleaned_code.upper()


def display_transcription(
    recognized_text: str,
    language_name: str,
) -> None:
    """Display recognized speech and detected language.

    Args:
        recognized_text: Text produced by Whisper.
        language_name: Readable detected-language name.
    """
    divider = "-" * DIVIDER_WIDTH

    print("Detected Language:")
    print(language_name)
    print()

    print("Recognized Text:")
    print(divider)
    print(recognized_text)
    print(divider)
    print()


def display_ai_response(response_text: str) -> None:
    """Display the text generated by Cohere.

    Args:
        response_text: AI response generated by the language model.
    """
    divider = "-" * DIVIDER_WIDTH

    print("AI Response:")
    print(divider)
    print(response_text)
    print(divider)
    print()


def save_text_file(
    text: str,
    file_path: Path,
) -> Path:
    """Save non-empty text to a UTF-8 file.

    Args:
        text: Text that will be saved.
        file_path: Destination text-file path.

    Returns:
        The path of the saved file.

    Raises:
        ValueError: If the supplied text is empty.
        OSError: If the destination cannot be prepared or written.
    """
    cleaned_text = text.strip()

    if not cleaned_text:
        raise ValueError(
            "Empty text cannot be saved."
        )

    file_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    file_path.write_text(
        cleaned_text + "\n",
        encoding="utf-8",
    )

    return file_path


def display_session_summary(
    *,
    recording_time: float,
    model_loading_time: float,
    transcription_time: float,
    llm_response_time: float,
    synthesis_time: float,
    playback_time: float,
    total_runtime: float,
    whisper_model: str,
    whisper_device: str,
    cohere_model: str,
    voice_name: str,
    language_name: str,
    transcript_character_count: int,
    response_character_count: int,
    recording_file: Path,
    transcript_file: Path,
    response_file: Path,
    response_audio_file: Path,
) -> None:
    """Display information about a completed assistant session.

    Args:
        recording_time: Time used to record microphone audio.
        model_loading_time: Time used to load Whisper.
        transcription_time: Time used to recognize speech.
        llm_response_time: Time used to generate the AI response.
        synthesis_time: Time used to generate response audio.
        playback_time: Time used to play the response audio.
        total_runtime: Total processing and playback time.
        whisper_model: Name of the active Whisper model.
        whisper_device: Processing device used by Whisper.
        cohere_model: Name of the Cohere model.
        voice_name: Name of the selected Windows speech voice.
        language_name: Detected spoken language.
        transcript_character_count: Number of transcript characters.
        response_character_count: Number of AI-response characters.
        recording_file: Path of the microphone recording.
        transcript_file: Path of the saved transcript.
        response_file: Path of the saved AI response.
        response_audio_file: Path of the generated response audio.
    """
    divider = "=" * DIVIDER_WIDTH

    print("Session Summary")
    print(divider)

    print("Processing Times")
    print(f"  Recording:          {recording_time:.2f} seconds")
    print(f"  Model Loading:      {model_loading_time:.2f} seconds")
    print(f"  Transcription:      {transcription_time:.2f} seconds")
    print(f"  LLM Response:       {llm_response_time:.2f} seconds")
    print(f"  Speech Synthesis:   {synthesis_time:.2f} seconds")
    print(f"  Audio Playback:     {playback_time:.2f} seconds")
    print(f"  Total Runtime:      {total_runtime:.2f} seconds")
    print()

    print("Models and Session")
    print(f"  Whisper Model:      {whisper_model}")
    print(f"  Whisper Device:     {whisper_device.upper()}")
    print(f"  Cohere Model:       {cohere_model}")
    print(f"  Speech Voice:       {voice_name}")
    print(f"  Language:           {language_name}")
    print(f"  Transcript Length:  {transcript_character_count} characters")
    print(f"  Response Length:    {response_character_count} characters")
    print()

    print("Generated Files")
    print(f"  Recording:          {recording_file}")
    print(f"  Transcript:         {transcript_file}")
    print(f"  AI Response:        {response_file}")
    print(f"  Response Audio:     {response_audio_file}")

    print(divider)